---
layout: post
title:  "Modules"
date:   2019-9-12 12:00:00
categories: python
permalink: /archivers/modules
comments: true
---
在项目中导入模块和包时，遇到了一点问题。查阅相关资料后做个小小总结.
<!--more-->
# 相关背景
## module
模块， 一个 py 文件或以其他文件形式存在的可被导入的就是一个模块.

## package
包，包含有 `__init__.py` 文件的文件夹.

## Python 解释器查找包的顺序
解释器查找包：

解释器会默认加载一些 `modules`，除了 `sys.builtin_module_names` 列出的内置模块之外，
还会加载其他一些标准库，都存放在 `sys.modules` 字典中.
然后是执行文件的所属目录，最后就是搜索 `sys.path` 路径下的模块了
(`sys.path[0]`默认存放的就是当前目录).

***

# 问题引入

现在有如下的项目结构.
```
$ project .
.
└──hello
    ├───hello
    │    ├──__init__.py
    │    ├── c.py
    │    └── d.py
    ├── a.py
    └── b.py
```
`d.py`
```python
def hello_d():
    print("hello, it's d.")
```
`c.py`
```python
from .d import hello_d
hello_d()
def hello_c():
    print("hello, it's c.")
```
`d.py`
```python
def hello_b():
    print("hello, it's b.")
```
`a.py`
```python
from hello.hello.c import hello_c
hello_c()
```
执行`$ project> python a.py`，报错
```
from hello.hello.c import hello_c
ModuleNotFoundError: No module named 'hello.hello'
```
没有找到`hello.hello`模块！

查看`sys.path`结果，里面没有`project`的绝对路径.
自然是不能找到`project/hello/hello`的.

于是通过`sys.append()`把`project`路径加到`sys.path`中.

在`a.py`加上这一句（或者使用`sys.path.insert()`）

`sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))`

此时`project`绝对路径就已经在`sys.path`中了.

可是执行`a.py`还是出现了上面一样的错误！

## 分析

在执行`a.py`时，解释器首先在当前路径寻找模块，根据`from hello.hello.c`,
于是就在内层的`hello`模块里面寻找`hello`,这显然就会报错，
因为我们写`from hello.hello.c`的初衷就是想让它从外层开始找.

而现在因为同名，导致导入模块时出错了.

## 解决
解决方法有如下几种：
* 不把`project`加入到`sys.path`，把`from hello.hello.c`改为
`from hello.c`.*（此种方法，Pycharm可能会提示报错，但是不影响程序执行，
把 `a.py` 的上级目录即外层 `hello` 设置为 `Sources Root` 就可以了）*
* 把`project`加入到`sys.path`，修改同名模块，此时`from hello.hello.c`变为
`from hello_one.hello_two.c`.
* 把可执行文件`a.py`放到与外层`hello`同级。（`project`加不加到`sys.path`都不影响）

# 另一个问题——关于**包内引用**
`.`：相对导入.

上面在`c.py`中通过`fomr .d import hello_d`引入了同级的d模块.
但是在执行文件`a.py`通过此种方式引入`b.py`中的`hello_b()`却会出现问题.

报错如下
```
from .b import hello_b
ModuleNotFoundError: No module named '__main__.b'; '__main__' is not a package
```
同样是引入同级的模块，其中一个却报错了.

## 解决

不同在于`a.py`是作为执行文件.

相对导入是基于当前模块的name属性的.当被执行模块作为python应用的主模块时，
因为其`name`属性为`'__main__'`，所以在调用其他模块时应使用绝对导入.

若`a.py`如下
```python
from hello.c import hello_c
hello_c()
from b import hello_b
hello_b()
```
结果：
```
hello, it's d.
hello, it's c.
hello, it's b.
```
***
# **参考**

[官方文档-模块](http://www.pythondoc.com/pythontutorial3/modules.html#tut-standardmodules)

[Python 模块的加载顺序](https://www.tuicool.com/articles/ENvIBnV)

[Python 包的引入顺序到底是怎样的？](https://segmentfault.com/q/1010000017357057)

[关于from . import和import的区别](https://www.cnblogs.com/yx179971/p/7615394.html)
